Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
stm32f4xx_it.c
usart.c
exRAM.c
spi.c
spi_flash.c
""")

# add Ethernet drivers.
if GetDepend('RT_USING_LWIP'):
    src += ['stm32f4xx_eth.c']

# add gpio drivers.
if GetDepend('RT_USING_PIN'):
    src += ['gpio.c']

if GetDepend('RT_USING_GUIENGINE'):
	src += ['drv_lcd.c']
	src += ['touch.c']
	src += ['touch_setup.c']
	
if GetDepend('RT_USING_USB_DEVICE') == True:
	src+= ['usb_bsp.c']
	src+= ['stm32f4xx_dcd.c']
	
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

