Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
application.c
startup.c
""")

	
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
