Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
application.c
startup.c
""")

if GetDepend('RT_USING_USB_DEVICE'):
    src += ['ramdisk.c']
	
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
