# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
src/asc12font.c
src/asc16font.c
src/blit.c
src/box.c
src/color.c
src/container.c
src/calibration.c
src/dc.c
src/dc_blend.c
src/dc_buffer.c
src/dc_client.c
src/dc_hw.c
src/dc_rotozoom.c
src/dc_trans.c
src/filerw.c
src/font.c
src/font_bmp.c
src/font_fnt.c
src/font_freetype.c
src/font_hz_bmp.c
src/font_hz_file.c
src/hz12font.c
src/hz16font.c
src/image.c
src/image_bmp.c
src/image_container.c
src/image_hdc.c
src/image_jpg.c
src/image_png.c
src/image_xpm.c
src/matrix.c
src/mouse.c
src/region.c
src/rtgui_app.c
src/rtgui_driver.c
src/rtgui_object.c
src/rtgui_system.c
src/server.c
src/title.c
src/topwin.c
src/widget.c
src/window.c
''')

widgets_src = Split("""
src/widgets/box.c
src/widgets/button.c
src/widgets/checkbox.c
src/widgets/combobox.c
src/widgets/iconbox.c
src/widgets/label.c
src/widgets/textview.c
src/widgets/listctrl.c
src/widgets/menu.c
src/widgets/progressbar.c
src/widgets/radiobox.c
src/widgets/slider.c
src/widgets/scrollbar.c
src/widgets/staticline.c
src/widgets/textbox.c
src/widgets/listbox.c
src/widgets/title.c
src/widgets/notebook.c
src/widgets/container.c
src/widgets/list_view.c
src/widgets/filelist_view.c
src/widgets/widget.c
src/widgets/window.c
src/widgets/panel.c
src/widgets/groupbox.c
src/widgets/edit.c
src/widgets/mv_view.c
src/widgets/plot.c
src/widgets/plot_curve.c
src/widgets/digtube.c
src/widgets/digfont.c
""")

#src = src + widgets_src

CPPPATH = [cwd + '/include']

group = []
if GetDepend('RT_USING_GUIENGINE'):
    group = DefineGroup('GUIEngine', src, depend = ['RT_USING_GUIENGINE'], CPPPATH = CPPPATH)

    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
