# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
demo/demo_view.c
demo/demo_view_button.c
demo/demo_view_label.c
demo/demo_application.c
demo/demo_view_checkbox.c
demo/demo_view_progressbar.c
demo/demo_view_scrollbar.c
demo/demo_view_textbox.c
demo/demo_view_radiobox.c
demo/demo_plot.c
demo/demo_view_animation.c
demo/demo_view_benchmark.c
demo/demo_view_combobox.c
demo/demo_view_digtube.c
demo/demo_view_listbox.c
demo/demo_view_listctrl.c
demo/demo_view_menu.c
demo/demo_view_notebook.c
demo/demo_view_slider.c
demo/demo_view_edit.c
demo/demo_view_image.c
demo/demo_view_dc.c
demo/demo_view_buffer_animation.c
src/rtgui_mv_model.c
src/asc12font.c
src/asc16font.c
src/blit.c
src/box.c
src/color.c
src/container.c
src/calibration.c
src/dc.c
src/dc_blend.c
src/dc_buffer.c
src/dc_client.c
src/dc_hw.c
src/dc_rotozoom.c
src/dc_trans.c
src/filerw.c
src/font.c
src/font_bmp.c
src/font_fnt.c
src/font_freetype.c
src/font_hz_bmp.c
src/font_hz_file.c
src/hz12font.c
src/hz16font.c
src/image.c
src/image_bmp.c
src/image_container.c
src/image_hdc.c
src/image_jpg.c
src/image_png.c
src/image_xpm.c
src/matrix.c
src/mouse.c
src/region.c
src/rtgui_app.c
src/rtgui_driver.c
src/rtgui_object.c
src/rtgui_system.c
src/server.c
src/title.c
src/topwin.c
src/widget.c
src/window.c
src/rtgui_theme.c
''')

widgets_src = Split("""
widgets/button.c
widgets/checkbox.c
widgets/combobox.c
widgets/iconbox.c
widgets/label.c
widgets/textview.c
widgets/listctrl.c
widgets/menu.c
widgets/progressbar.c
widgets/radiobox.c
widgets/slider.c
widgets/scrollbar.c
widgets/staticline.c
widgets/textbox.c
widgets/listbox.c
widgets/notebook.c
widgets/list_view.c
widgets/filelist_view.c
widgets/panel.c
widgets/groupbox.c
widgets/edit.c
widgets/mv_view.c
widgets/plot.c
widgets/plot_curve.c
widgets/digtube.c
widgets/digfont.c
""")

src = src + widgets_src

CPPPATH = [cwd + '/include']
CPPPATH = CPPPATH + ['/demo']

group = []
if GetDepend('RT_USING_GUIENGINE'):
    group = DefineGroup('GUIEngine', src, depend = ['RT_USING_GUIENGINE'], CPPPATH = CPPPATH)

    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
